version: '3.8'

services:
  web:
    build: .
    container_name: alkinvaran_web
    restart: always
    command: >
      bash -c "python manage.py collectstatic --noinput &&
               python manage.py migrate &&
               gunicorn alkinvaran_proj.wsgi:application --bind 0.0.0.0:8000 --workers 3"
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - ./media:/app/media
      - static_volume:/app/staticfiles
    env_file:
      - .env

  nginx:
    image: nginx:1.25
    container_name: alkinvaran_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./media:/app/media
      - static_volume:/app/staticfiles
    depends_on:
      - web

volumes:
  static_volume:
