version: '3.8'

services:
  web:
    build: .
    container_name: alkinvaran_web
    restart: always
    command: >
      bash -c "python manage.py collectstatic --noinput &&
               python manage.py migrate &&
               gunicorn alkinvaran_proj.wsgi:application --bind 0.0.0.0:8000 --workers 3"
    volumes:
      - sqlite_volume:/app/data
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    env_file:
      - .env
    environment:
      - SQLITE_DB_PATH=/app/data/db.sqlite3

  nginx:
    image: nginx:1.25
    container_name: alkinvaran_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - web

volumes:
  sqlite_volume:
  static_volume:
  media_volume:
