# Generated by Django 4.2.28 on 2026-03-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Ad Soyad')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=200, verbose_name='Konu')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Gönderim Tarihi')),
            ],
            options={
                'verbose_name': 'İletişim Mesajı',
                'verbose_name_plural': 'İletişim Mesajları',
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Disiplin Adı')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('image', models.ImageField(upload_to='disciplines/', verbose_name='Görsel')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
            ],
            options={
                'verbose_name': 'Disiplin',
                'verbose_name_plural': 'Disiplinler',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('subtitle', models.TextField(verbose_name='Alt Başlık')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Video URL (Opsiyonel)')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='hero/', verbose_name='Arka Plan Görseli')),
                ('button_text', models.CharField(default='Bize Ulaşın', max_length=50, verbose_name='Buton Metni')),
            ],
            options={
                'verbose_name': 'Hero Bölümü',
                'verbose_name_plural': 'Hero Bölümü',
            },
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Stüdyo Adı')),
                ('location', models.CharField(max_length=255, verbose_name='Konum')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('image', models.ImageField(upload_to='studios/', verbose_name='Görsel')),
                ('instagram_link', models.URLField(blank=True, null=True, verbose_name='Instagram Linki')),
                ('map_link', models.URLField(blank=True, null=True, verbose_name='Google Harita Linki')),
            ],
            options={
                'verbose_name': 'Stüdyo',
                'verbose_name_plural': 'Stüdyolar',
            },
        ),
        migrations.CreateModel(
            name='TrainingLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('beg', 'Başlangıç'), ('int', 'Orta'), ('adv', 'İleri')], max_length=50, verbose_name='Seviye')),
                ('title', models.CharField(max_length=100, verbose_name='Seviye Başlığı')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('icon_name', models.CharField(help_text='Lucide icon name or emoji', max_length=50, verbose_name='İkon')),
            ],
            options={
                'verbose_name': 'Eğitim Seviyesi',
                'verbose_name_plural': 'Eğitim Seviyeleri',
            },
        ),
    ]
