# Generated by Django 4.2.28 on 2026-03-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Danışan/İletişim Mesajı', 'verbose_name_plural': 'Gelen Kutusu (CRM)'},
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='admin_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Yönetici Notları (Sadece siz görürsünüz)'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='is_replied',
            field=models.BooleanField(default=False, verbose_name='Dönüş Yapıldı'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='disciplines/', verbose_name='Görsel'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='studios/', verbose_name='Görsel'),
        ),
    ]
