# Generated by Django 4.2.28 on 2026-03-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_contactmessage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon Numarası'),
        ),
    ]
