# Generated by Django 4.2.28 on 2026-03-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_contactmessage_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portrait_image', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Hakkımda Profil Görseli')),
            ],
            options={
                'verbose_name': 'Hakkımda Bölümü',
                'verbose_name_plural': 'Hakkımda Bölümü',
            },
        ),
    ]
