# Generated by Django 4.2.28 on 2026-03-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_aboutsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='content',
            field=models.TextField(default='Ben Alkin Varan...', verbose_name='Hakkımda İçeriği'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='highlight_title',
            field=models.CharField(default='Mimarisi', max_length=100, verbose_name='Vurgulu Başlık'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='title',
            field=models.CharField(default='Hareketin', max_length=100, verbose_name='Ana Başlık'),
        ),
    ]
