# Generated by Django 4.2.28 on 2026-03-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_aboutsection_content_aboutsection_highlight_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='SEO URL (Otomatik Dolur)')),
                ('content', models.TextField(verbose_name='Metin/İçerik')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Kapak Görseli')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yazılma Tarihi')),
            ],
            options={
                'verbose_name': 'Blog Yazısı',
                'verbose_name_plural': 'Blog Yazıları',
                'ordering': ['-created_at'],
            },
        ),
    ]
