# Generated by Django 4.2.28 on 2026-03-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255, verbose_name='Gizli Cihaz Kimliği')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('message', models.TextField(verbose_name='Bildirim İçeriği')),
                ('is_read', models.BooleanField(default=False, verbose_name='Okundu mu?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
            ],
            options={
                'verbose_name': 'Uygulama İçi Bildirim',
                'verbose_name_plural': 'Uygulama İçi Bildirimler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='device_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Gizli Cihaz Kimliği'),
        ),
    ]
