upstream alkinvaran_app {
    server web:8000;
}

server {
    listen 80;
    server_name alkinvaran.com www.alkinvaran.com;

    # Gelen standard HTTP (80) trafiklerini doğrudan HTTPS'ye yönlendiriyoruz.
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name alkinvaran.com www.alkinvaran.com;

    # SSL Sertifika yolları (Certbot'un AWS üzerinde oluşturacağı gerçek yollar)
    ssl_certificate /etc/letsencrypt/live/alkinvaran.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/alkinvaran.com/privkey.pem;

    location / {
        proxy_pass http://alkinvaran_app;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_redirect off;
    }

    location /static/ {
        alias /app/staticfiles/;
    }

    location /media/ {
        alias /app/media/;
    }
}
