upstream alkinvaran_app {
    server web:8000;
}

server {
    listen 80;
    server_name alkinvaran.com www.alkinvaran.com;

    location / {
        proxy_pass http://alkinvaran_app;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    location /static/ {
        alias /app/staticfiles/;
    }

    location /media/ {
        alias /app/media/;
    }

    # SSL configuration will be active after you use certbot
    # Make sure to install certbot and configure properly on your server.
}
