# Generated by Django 4.2.28 on 2026-03-16 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Öğrenci Adı Soyadı')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-posta')),
                ('registration_date', models.DateField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('inactive', 'Pasif')], default='active', max_length=20, verbose_name='Durum')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Özel Notlar')),
            ],
            options={
                'verbose_name': 'Öğrenci',
                'verbose_name_plural': 'Öğrenciler',
                'ordering': ['-registration_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tutar (₺)')),
                ('payment_date', models.DateField(verbose_name='Ödeme Tarihi')),
                ('payment_method', models.CharField(choices=[('cash', 'Nakit'), ('transfer', 'EFT/Havale'), ('cc', 'Kredi Kartı')], default='transfer', max_length=20, verbose_name='Ödeme Yöntemi')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Açıklama (Örn: Mart Ayı Aidatı)')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='crm.student', verbose_name='Öğrenci')),
            ],
            options={
                'verbose_name': 'Ödeme',
                'verbose_name_plural': 'Ödemeler',
                'ordering': ['-payment_date'],
            },
        ),
    ]
