# Generated by Django 4.2.28 on 2026-03-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ders Adı (Örn: Çocuk Cimnastik)')),
                ('day_of_week', models.CharField(choices=[('1', 'Pazartesi'), ('2', 'Salı'), ('3', 'Çarşamba'), ('4', 'Perşembe'), ('5', 'Cuma'), ('6', 'Cumartesi'), ('7', 'Pazar')], max_length=1, verbose_name='Gün')),
                ('time', models.TimeField(verbose_name='Saat')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Açıklama/Notlar')),
            ],
            options={
                'verbose_name': 'Ders',
                'verbose_name_plural': 'Dersler',
                'ordering': ['day_of_week', 'time'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='lessons',
            field=models.ManyToManyField(blank=True, related_name='students', to='crm.lesson', verbose_name='Kayıtlı Olduğu Dersler'),
        ),
    ]
