# Generated by Django 4.2.28 on 2026-03-16 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_lesson_student_lessons'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='crm.lesson', verbose_name='İlgili Ders'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_month',
            field=models.IntegerField(blank=True, choices=[(1, 'Ocak'), (2, 'Şubat'), (3, 'Mart'), (4, 'Nisan'), (5, 'Mayıs'), (6, 'Haziran'), (7, 'Temmuz'), (8, 'Ağustos'), (9, 'Eylül'), (10, 'Ekim'), (11, 'Kasım'), (12, 'Aralık')], null=True, verbose_name='Ödeme Ayı'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ödeme Yılı'),
        ),
    ]
