# Generated by Django 4.2.28 on 2026-03-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_payment_lesson_payment_payment_month_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tutar (₺)')),
                ('date', models.DateField(verbose_name='Gider Tarihi')),
                ('category', models.CharField(choices=[('rent', 'Kira / Alan Aidatı'), ('salary', 'Maaş / Personel'), ('bills', 'Fatura (Elektrik/Su/İnternet)'), ('equipment', 'Ekipman / Malzeme'), ('marketing', 'Reklam / Pazarlama'), ('other', 'Diğer')], default='other', max_length=20, verbose_name='Kategori')),
                ('description', models.CharField(max_length=255, verbose_name='Açıklama / Detay')),
                ('expense_month', models.IntegerField(blank=True, choices=[(1, 'Ocak'), (2, 'Şubat'), (3, 'Mart'), (4, 'Nisan'), (5, 'Mayıs'), (6, 'Haziran'), (7, 'Temmuz'), (8, 'Ağustos'), (9, 'Eylül'), (10, 'Ekim'), (11, 'Kasım'), (12, 'Aralık')], null=True, verbose_name='İlgili Ay')),
                ('expense_year', models.IntegerField(blank=True, null=True, verbose_name='İlgili Yıl')),
            ],
            options={
                'verbose_name': 'Gider',
                'verbose_name_plural': 'Giderler',
                'ordering': ['-date'],
            },
        ),
    ]
