# Generated by Django 4.2.28 on 2026-03-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('rent', 'Kira / Alan Aidatı'), ('salary', 'Maaş / Personel'), ('bills', 'Fatura (Elektrik/Su/İnternet)'), ('equipment', 'Ekipman / Malzeme'), ('marketing', 'Reklam / Pazarlama'), ('cleaning', 'Temizlik / Hijyen'), ('other', 'Diğer')], default='other', max_length=20, verbose_name='Kategori'),
        ),
    ]
